name: zube-sync
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review, synchronize ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: script
      run: .github/workflows/scripts/pr.sh "${{ secrets.GITHUB_TOKEN }}"

