name: zube-integration
on:
  pull_request:
    types: [ opened, reopened, edited, closed ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: fetch-scripts
      run: |
        mkdir -p .github/workflows/scripts
        pushd .github/workflows/scripts
        wget https://raw.githubusercontent.com/nwmac/ghtest/main/.github/workflows/scripts/pr.js
        wget https://raw.githubusercontent.com/nwmac/ghtest/main/.github/workflows/scripts/request.js
        popd
    - name: run-script
      run: node .github/workflows/scripts/pr.js "${{ secrets.GITHUB_TOKEN }}"

