name: zube-integration
on:
  pull_request:
    types: [ opened, reopened, edited, closed ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: script1
      run: node --version
    - name: script2
      run: git version
    - name: clone
      run: ls -al .github/workflows/scripts
    - name: script
      run: node .github/workflows/scripts/pr.js "${{ secrets.GITHUB_TOKEN }}"

